[tools]
tailwindcss = "4.3.3"

[build]
target = "index.html"
dist = "dist"
release = true
minify = "on_release"
public_url = "/"        # since Pages source will be a user/repo root now, not a subpath — see note below
filehash = false