[package]
name = "source"
version = "0.1.0"
edition = "2024"

[build-dependencies]
serde_json = "1.0.143"

[dependencies]
gloo-net = { version = "0.6.0", features = ["json"] }
leptos = { version = "0.8.6", features = ["csr"] }
leptos_meta = "0.8.5"
web-sys = "0.3.77"
